name: Release
on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Release tag to publish"
        required: true
jobs:
  dorelease:
    name: release
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
      - name: publish to sonatype
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          VERSION: ${{ github.event.inputs.release_tag }}
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publishToSonatype closeAndReleaseStagingRepository # closeSonatypeStagingRepository TODO: select based on input tag

      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: kotlin/lib/build/libs
